<?php

namespace App\Console\Commands;

use Illuminate\Console\Command;
use Illuminate\Support\Facades\File;

/**
 * Fills in the Zero-Knowledge encryption secrets required by
 * app/Helpers/EncryptionHelper.php (see docs/encryption_refactor.md).
 *
 * Mirrors the UX of `key:generate`/`jwt:secret`: only fills blank values by
 * default, writes in place, and warns loudly before overwriting anything
 * that's already in use (rotating these breaks existing data).
 */
class GenerateEncryptionSecrets extends Command
{
    protected $signature = 'uangku:generate-secrets
        {--force : Overwrite values that are already set (breaks existing PIN hashes, email lookups, and auth verifiers!)}
        {--show : Print the values without writing them to .env}';

    protected $description = 'Generate the MAIN_SALT_KEY / MAIN_SYSTEM_KEY / MAIN_BLIND_INDEX_KEY / ADMIN_SECRET_KEY secrets needed for Zero-Knowledge encryption';

    /**
     * @var array<string, callable(): string>
     */
    private array $secrets;

    public function __construct()
    {
        parent::__construct();

        $this->secrets = [
            'MAIN_SALT_KEY' => fn () => bin2hex(random_bytes(16)),
            'MAIN_SYSTEM_KEY' => fn () => bin2hex(random_bytes(32)),
            'MAIN_BLIND_INDEX_KEY' => fn () => bin2hex(random_bytes(32)),
            'ADMIN_SECRET_KEY' => fn () => $this->generateSecretKeyFormat(),
        ];
    }

    public function handle(): int
    {
        $envPath = base_path('.env');

        if (! File::exists($envPath)) {
            $this->error('.env not found. Copy .env.example to .env first (or run `cp .env.example .env`).');

            return self::FAILURE;
        }

        $env = File::get($envPath);
        $force = (bool) $this->option('force');
        $showOnly = (bool) $this->option('show');

        if ($force && ! $showOnly) {
            $this->warn('--force will overwrite existing values. Any account whose PIN/session/email lookup');
            $this->warn('relies on the CURRENT keys will break (bcrypt hashes and blind-index lookups become');
            $this->warn('unverifiable). Only do this on a fresh install, or if you know what you\'re doing.');

            if (! $this->confirm('Continue?')) {
                return self::SUCCESS;
            }
        }

        $rows = [];

        foreach ($this->secrets as $key => $generator) {
            $current = $this->currentValue($env, $key);
            $hasValue = $current !== null && $current !== '';

            if ($hasValue && ! $force) {
                $rows[] = [$key, 'skipped (already set)', $this->mask($current)];

                continue;
            }

            $value = $generator();
            $rows[] = [$key, $hasValue ? 'regenerated' : 'generated', $this->mask($value)];

            if (! $showOnly) {
                $env = $this->setEnvValue($env, $key, $value);
            }
        }

        $this->table(['Key', 'Status', 'Value (masked)'], $rows);

        if ($showOnly) {
            $this->info('--show: nothing was written. Drop these into your .env manually if they look right.');

            return self::SUCCESS;
        }

        File::put($envPath, $env);
        $this->info('.env updated.');
        $this->line('Run <comment>php artisan config:clear</comment> if the app was already booted with the old values.');

        return self::SUCCESS;
    }

    private function currentValue(string $env, string $key): ?string
    {
        if (preg_match('/^'.preg_quote($key, '/').'=(.*)$/m', $env, $matches)) {
            return trim($matches[1]);
        }

        return null;
    }

    private function setEnvValue(string $env, string $key, string $value): string
    {
        $pattern = '/^'.preg_quote($key, '/').'=.*$/m';

        if (preg_match($pattern, $env)) {
            return preg_replace($pattern, "{$key}={$value}", $env);
        }

        return rtrim($env)."\n{$key}={$value}\n";
    }

    private function mask(string $value): string
    {
        if (strlen($value) <= 8) {
            return str_repeat('*', strlen($value));
        }

        return substr($value, 0, 4).str_repeat('*', 8).substr($value, -4);
    }

    /**
     * UANGKU-XXXXXX-XXXXXX-XXXXX-XXXXX-XXXXX — same shape as the client-side
     * secret key, used only as a fixed value for the local dev/seed admin
     * account (see database/seeders/UserSeeder.php). Real user secret keys
     * are never generated by the server.
     */
    private function generateSecretKeyFormat(): string
    {
        $raw = strtoupper(str_replace(['=', '+', '/'], '', base64_encode(random_bytes(24))));

        return 'UANGKU-'.
            substr($raw, 0, 6).'-'.
            substr($raw, 6, 6).'-'.
            substr($raw, 12, 5).'-'.
            substr($raw, 17, 5).'-'.
            substr($raw, 22, 5);
    }
}
