version: "3.8"

services:
  api:
    container_name: api
    image: oratakashi/uangku-be:dev
    entrypoint: php artisan octane:frankenphp
    ports:
      - "80:8000"
    depends_on:
      - mariadb
      - redis
      - minio
    networks:
      - uangku-network  # <-- Referensi network di bawah
    deploy:
      resources:
        limits:
          memory: 512M

  mariadb:
    container_name: mariadb
    image: mariadb:latest
    restart: always
    ports:
      - "3306:3306"
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_PASSWORD}
      MARIADB_ROOT_HOST: '%'
    deploy:
      resources:
        limits:
          memory: 128M
    volumes:
      - ~/mysql:/var/lib/mysql
    networks:
      - uangku-network

  redis:
    container_name: redis
    image: redis:latest
    deploy:
      resources:
        limits:
          memory: 128M
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_PASSWORD}
    volumes:
      - ~/redis:/data
    networks:
      - uangku-network

  minio:
    container_name: minio
    image: minio/minio:RELEASE.2025-04-22T22-12-26Z
    restart: always
    ports:
      - '9000:9000'
      - '9001:9001'
    deploy:
      resources:
        limits:
          memory: 128M
    networks:
      - uangku-network
    volumes:
      - /home/oratakashi/minio:/bitnami/minio/data
    environment:
      - MINIO_ROOT_USER=${MINIO_USERNAME}
      - MINIO_ROOT_PASSWORD=${MINIO_PASSWORD}
      - MINIO_DEFAULT_BUCKETS=${AWS_BUCKET}
      - MINIO_ADDRESS=:9000
      - MINIO_CONSOLE_ADDRESS=:9001
    command: minio server /bitnami/minio/data

networks:
  uangku-network:  # <-- Ini bagian penting, jangan sampai typo
    driver: bridge
