version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: php artisan octane:frankenphp
    ports:
      - "80:8000"
    volumes:
      - .:/app
  mariadb:
    container_name: mariadb
    image: mariadb:latest
    restart: always
    ports:
      - 3306:3306
    environment:
      MARIADB_ROOT_PASSWORD: root
    volumes:
      - ~/mysql:/var/lib/mysql
  redis:
    container_name: redis
    image: redis:latest
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass root
    volumes:
        - ~/redis:/data
#  phpmyadmin:
#    container_name: phpmyadmin
#    image: phpmyadmin
#    restart: always
#    ports:
#      - 80:80
#    environment:
#      - PMA_HOST=mariadb
#      - PMA_PORT=3306
#    depends_on:
#      - mariadb

